---

- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600


- name: 'Uninstall old versions'
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  ignore_errors: yes


# Install the following deps:
- name: 'Install Docker CE dependencies'
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present


- name: Download Docker gpg key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/dockergpg


- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    mode: 0755
    state: directory


- name: Check if gpg file exists
  stat:
    path: /etc/apt/keyrings/docker.gpg
  register: gpg_docker_file_exists


- name: De-Armor Docker GPG key
  command:  gpg -o /etc/apt/keyrings/docker.gpg --dearmor /tmp/dockergpg
  when: not gpg_docker_file_exists.stat.exists


- name: Set key file permissions
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: 0644


- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture


- name: "Add Docker's repository to APT sources list"
  apt_repository:
    repo: "deb [arch={{deb_architecture.stdout}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present


- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600


- name: 'Install containerd package'
  apt:
    name:
      - containerd
      - containerd.io
    state: present


- name: 'Enable containerd service and ensure it (re)starts at boot'
  service:
    name: 'containerd'
    state: 'started'
    enabled: 'yes'


- name: Create etc containerd directory
  file:
    path: /etc/containerd
    mode: 0755
    state: directory


- name: 'Generate default containerd config'
  shell: containerd config default > /etc/containerd/config.toml


- name: 'Set cgroup driver for runc to systemd'
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify:
    - Restart containerd

