---
#
# Set variables for RHEL/CentOS variants
#

- name: Set NFS server variables (RHEL/CentOS 7.x)
  tags:
    - nfs
    - nfs-server
  set_fact:
    nfs_server_services:
      - nfs-server
    nfs_server_packages:
      - nfs-utils
    _nfs_server_started_state: 'started'

