---
#
# Install an NFSv4 server
#

- name: Load distribution-specific parameters
  include_tasks: 'init-{{ansible_os_family}}.yml'
  tags:
    - nfs
    - nfs-server

- name: install NFS server software
  tags:
    - nfs
    - nfs-server
  package:
    pkg: '{{nfs_server_packages}}'
    state: present


- name: Ensure export directories exist
  tags:
    - nfs
    - nfs-server
  file:
    path: "{{item.path}}"
    state: directory
  loop: '{{NFS_EXPORTS}}'


# exports need to be there before attempting to install/start the
# server, otherwise the service startup script might refuse to start
# the NFS server
- name: Export directories
  tags:
    - nfs
    - nfs-server
  lineinfile:
    dest: '/etc/exports'
    create: yes
    backup: yes
    line: '{{item.path}} {% for client in item.clients %}{{client}}({{item.options|default("async,rw,no_root_squash,no_subtree_check,crossmnt")}}) {% endfor %}'
    # replace clients+options on the given path
    regexp: '^ *{{item.path}} +'
    state: present
  loop: '{{NFS_EXPORTS}}'


- name: Ensure portmapper is running
  tags:
    - nfs
    - nfs-server
  service:
    name: 'rpcbind'
    enabled: yes
    state: 'started'


- name: Ensure NFS server is running
  tags:
    - nfs
    - nfs-server
  service:
    name: '{{item}}'
    enabled: yes
    state: '{{_nfs_server_started_state}}'
  loop: '{{nfs_server_services}}'


- name: Reload NFS exports file
  tags:
    - nfs
    - nfs-server
  command:
    exportfs -r
