---

- name: Check that the /etc/kubernetes/kubelet.conf exists
  stat:
    path: /etc/kubernetes/kubelet.conf
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: kubelet_presence

- name: Join Kubernetes cluster
  command: |
    kubeadm join --discovery-token-unsafe-skip-ca-verification --token {{ktoken}} {{kubernetes_master}}:{{kubernetes_default_port}}
  when: kubelet_presence.stat.exists == False
