---

kubernetes_default_networking: calico
kubernetes_network: 10.32.0.0/12
kubernetes_service_network: 10.96.0.0/12

#ktoken: "c6b4fe.{{ (morpheus['instance']['apps'][0]['id'] | hash('md5'))[:16] }}"
ktoken: "1ewc2e.c6b4fec6b4fec6b4"

# Flannel network works on amd64, arm, arm64 and ppc64le platform
# see https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#instructions

kubernetes_networking:
  weave:
    manifest: https://cloud.weave.works/k8s/net
  calico:
    manifest: https://docs.projectcalico.org/manifests/calico.yaml 
  canal:
    rbac: https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/1.7/rbac.yaml
    manifest: https://raw.githubusercontent.com/projectcalico/canal/master/k8s-install/1.7/canal.yaml
  flannel:
    manifest: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    platform: amd64


# Packages install state
pkg_install_state: 'present'
