---

- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600


- name: 'Uninstall old versions'
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  ignore_errors: yes


# Install the following deps:
- name: 'Install Docker CE dependencies'
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present


- name: Download Docker gpg key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/dockergpg

- name: De-Armor Docker GPG key
  command:  gpg --dearmor /tmp/dockergpg -o /etc/apt/keyrings/docker.gpg


- name: Set key file permissions
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: 0644


- name: "Add Docker's repository to APT sources list"
  apt_repository:
    repo: "deb [arch={{ansible_architecture}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present


- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600


- name: 'Install Docker packages'
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present


- name: 'Enable Docker service and ensure it (re)starts at boot'
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'


- name: 'Enable containerd service and ensure it (re)starts at boot'
  service:
    name: 'containerd'
    state: 'started'
    enabled: 'yes'


# Add more users to the `docker` group
- name: 'Add users to docker group'
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
  loop: '{{ docker_group_members }}'
