---
#
# Install and configure prerequisites
# Ref. : https://kubernetes.io/docs/setup/production-environment/container-runtimes/#install-and-configure-prerequisites
#
- name: Install and configure network prerequisites
  include_tasks: 'network-prerequisites.yml'

#
# Install Docker Community Edition
# See: https://docs.docker.com/install/
#

- name: Perform distribution-dependent steps
  include_tasks: 'install-{{ansible_distribution}}.yml'


