---

#
# Forwarding IPv4 and letting iptables see bridged traffic
# Ref: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
#

- name: Copy modules conf for k8s
  copy:
    src: 'etc/modules-load.d/k8s.conf'
    dest: '/etc/modules-load.d/k8s.conf'


- name: load overlay module
  modprobe:
    name: overlay
    state: present


- name: load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present


- name: Copy sysctl params for k8s
  copy:
    src: 'etc/sysctl.d/k8s.conf'
    dest: '/etc/sysctl.d/k8s.conf'


- name: Reload sysctl
  command: sysctl --system
