---

- name: Install Kubernetes master
  hosts: all
  tags:
    - containerd
    - kubernetes
    - master
  roles:
    - kubernetes-master
  tasks:
  - name: Create kube directory for normal user
    file:
      path: "/opt/k8s"
      state: directory
      mode: 0755

  - name: Copy configuration into kube directory to allow normal user to access it
    copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf
      dest: "/opt/k8s/config"
      mode: 0444

