---
- name: Partition and format disk
  hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
  - name: install parted
    package:
      name: parted
      state: present

  - name: Partition the disk volume
    parted: 
      device: /dev/vdb 
      unit: MiB
      label: gpt
      number: 1
      part_start: "0%"
      part_end: "100%"
      part_type: primary
      state: present

  - name: Create a ext4 filesystem on /dev/vdb1
    filesystem:
      fstype: ext4
      dev: /dev/vdb1

  - name: Create mount directory
    file:
      path: /data
      state: directory

  - name: Mount volume in selected directory
    mount:
      path: /data
      src: /dev/vdb1
      fstype: ext4
      state: mounted

- name: Configure nfs server
  tags:
    - nfs
  hosts: all
  become: yes
  roles:
    - role: nfs-server

- name: 
  hosts: all
  become: yes
  tasks:
  - firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - nfs
      - rpc-bind
      - mountd

