---
- name: Morpheus variable print
  hosts: all
  vars:
    ktoken: "c6b4fe.{{ (morpheus['instance']['apps'][0]['id'] | hash('md5'))[:16] }}"
    myuser: "{{ morpheus['server']['sshUsername'] }}"
  tasks:
    - name: Print morpheus variable
      debug:
        msg: "My user is : {{ myuser }}"
